package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptColorReference = createDescriptorForColorReference();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptColor, myConceptColorReference, myConceptShape, myConceptSquare);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.ColorReference:
        return myConceptColorReference;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Canvas", 0xba214374e0fb4e8eL, 0x8290609857bfc289L, 0x1656b572aee174fbL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:c9455df6-ec66-4063-8223-c47dafef9eaf(Shapes.structure)/1609673420996441339");
    b.version(3);
    b.aggregate("shapes", 0x1656b572aee174feL).target(0xba214374e0fb4e8eL, 0x8290609857bfc289L, 0x1656b572aee174f2L).optional(true).ordered(true).multiple(true).origin("1609673420996441342").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Circle", 0xba214374e0fb4e8eL, 0x8290609857bfc289L, 0x1656b572aee174f3L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0xba214374e0fb4e8eL, 0x8290609857bfc289L, 0x1656b572aee174f2L);
    b.origin("r:c9455df6-ec66-4063-8223-c47dafef9eaf(Shapes.structure)/1609673420996441331");
    b.version(3);
    b.property("x", 0x1656b572aee174f4L).type(PrimitiveTypeId.INTEGER).origin("1609673420996441332").done();
    b.property("y", 0x1656b572aee174f5L).type(PrimitiveTypeId.INTEGER).origin("1609673420996441333").done();
    b.property("radius", 0x1656b572aee174f6L).type(PrimitiveTypeId.INTEGER).origin("1609673420996441334").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Color", 0xba214374e0fb4e8eL, 0x8290609857bfc289L, 0x1656b572aee27808L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c9455df6-ec66-4063-8223-c47dafef9eaf(Shapes.structure)/1609673420996507656");
    b.version(3);
    b.alias("color");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColorReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "ColorReference", 0xba214374e0fb4e8eL, 0x8290609857bfc289L, 0x1656b572aee3e922L);
    b.class_(false, false, false);
    b.origin("r:c9455df6-ec66-4063-8223-c47dafef9eaf(Shapes.structure)/1609673420996602146");
    b.version(3);
    b.associate("target", 0x1656b572aee3e924L).target(0xba214374e0fb4e8eL, 0x8290609857bfc289L, 0x1656b572aee27808L).optional(false).origin("1609673420996602148").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Shape", 0xba214374e0fb4e8eL, 0x8290609857bfc289L, 0x1656b572aee174f2L);
    b.class_(false, true, false);
    b.origin("r:c9455df6-ec66-4063-8223-c47dafef9eaf(Shapes.structure)/1609673420996441330");
    b.version(3);
    b.aggregate("color", 0x1656b572aee3e930L).target(0xba214374e0fb4e8eL, 0x8290609857bfc289L, 0x1656b572aee3e922L).optional(false).ordered(true).multiple(false).origin("1609673420996602160").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Square", 0xba214374e0fb4e8eL, 0x8290609857bfc289L, 0x1656b572aee174f7L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0xba214374e0fb4e8eL, 0x8290609857bfc289L, 0x1656b572aee174f2L);
    b.origin("r:c9455df6-ec66-4063-8223-c47dafef9eaf(Shapes.structure)/1609673420996441335");
    b.version(3);
    b.property("upperLeftX", 0x1656b572aee174f8L).type(PrimitiveTypeId.INTEGER).origin("1609673420996441336").done();
    b.property("upperLeftY", 0x41b574674125cacaL).type(PrimitiveTypeId.INTEGER).origin("4734818570073393866").done();
    b.property("size", 0x41b574674125cacbL).type(PrimitiveTypeId.INTEGER).origin("4734818570073393867").done();
    b.alias("square");
    return b.create();
  }
}
